image: Visual Studio 2019

build: off

test_script:
- ps: 'Get-ChildItem env: | Out-String | Set-Content vars.txt'

artifacts:
- path: agentpkg
  name: WinApp
- path: vars.txt

deploy:
- provider: Environment
  name: test-agent-delete-me
